 spring:
   autoconfigure:
     exclude:
       - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
       - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

 mongodb:
   replicaset:
     name: docker-rs
     username: admin
     password: admin
     primary: mongo1
     port: 9042
     database: mongo-webflux
     authentication-database: admin
